# Generated by Django 3.1.4 on 2020-12-26 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201226_2014'),
        ('blog', '0003_auto_20201226_1750'),
    ]

    operations = [
    ]
